routes/web.php
<?php

use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes(['register' => false]);

Route::middleware(['web'])->prefix('dashboard')->group(function () {
    Route::get('/', function(){
        return view('admin.dashboard');
    })->name('DashboardHome');

    Route::resource('company', CompanyController::class);

    Route::resource('employee', EmployeeController::class);
});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CompanyRequest;
use App\Models\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::paginate(10);

        return view('admin.companies.index', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CompanyRequest $request)
    {
        $company = new Company();
        $company->name = $request->name;
        $company->url = $request->url;
        $company->email = $request->email;
        $company->logo = Storage::disk('public')->put('logos/', $request->logo);
        try{
            $company->save();
        } catch(\Exception $e){
            return back()->with('error', $e->getMessage()); 
        }

        return back()->with('success', 'A new company has been added!');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $company = Company::findOrFail($id);

        return view('admin.companies.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $company = Company::findOrFail($id);
        $company->name = $request->name;
        $company->url = $request->url;
        $company->email = $request->email;
        if($request->logo){
            Storage::disk('public')->delete($company->logo);
            $company->logo = Storage::disk('public')->put('logos/', $request->logo);
        }
        try{
            $company->save();
        } catch(\Exception $e){
            return back()->with('error', $e->getMessage()); 
        }

        return back()->with('success', 'Updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Company::where('id', $id)->delete();

        return back()->with('success', 'Deleted successfully!');
    }
}

resources/views/admin/companies/create.blade.php
@extends('layouts/layout/layout')

@section('head')
<title>Create a company</title>
@endsection

@section('body')
	<!--begin::Portlet-->
    <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
                        Create a company
                    </h3>
                </div>
            </div>

            <!--begin::Form-->
            <form class="kt-form" method="POST" action="{{route('company.store')}}" enctype="multipart/form-data">
                @csrf
                <div class="kt-portlet__body">
                    <div class="form-group">
                        <label>name</label>
                        <input type="text" class="form-control" name="name" value="{{old('name')}}" required>
                        @if ($errors->has('name'))
                        <span class="help-block" style="color: red">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" class="form-control" name="email" value="{{old('email')}}" required>
                        @if ($errors->has('email'))
                        <span class="help-block" style="color: red">{{ $errors->first('email') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>url</label>
                        <input type="url" class="form-control" name="url" value="{{old('name')}}" required>
                        @if ($errors->has('url'))
                        <span class="help-block" style="color: red">{{ $errors->first('url') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>Logo</label>
                        <input type="file" class="form-control" name="logo" required>
                        @if ($errors->has('logo'))
                        <span class="help-block" style="color: red">{{ $errors->first('logo') }}</span>
                        @endif
                    </div>
                </div>
                <div class="kt-portlet__foot">
                    <div class="kt-form__actions">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>

            <!--end::Form-->
        </div>

@stop
@section('scripts')
<script>
</script>
@stop

resources/views/admin/companies/edit.blade.php
@extends('layouts/layout/layout')

@section('head')
<title>Edit a company</title>
@endsection

@section('body')
	<!--begin::Portlet-->
    <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
                        Edit a company
                    </h3>
                </div>
            </div>

            <!--begin::Form-->
            <form class="kt-form" method="POST" action="{{route('company.update', $company->id)}}" enctype="multipart/form-data">
                @csrf
                @method('PUT')
                <div class="kt-portlet__body">
                    <div class="form-group">
                        <label>name</label>
                        <input type="text" class="form-control" name="name" value="{{$company->name}}" required>
                        @if ($errors->has('name'))
                        <span class="help-block" style="color: red">{{ $errors->first('name') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="email" class="form-control" name="email" value="{{$company->email}}" required>
                        @if ($errors->has('email'))
                        <span class="help-block" style="color: red">{{ $errors->first('email') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>url</label>
                        <input type="url" class="form-control" name="url" value="{{$company->url}}" required>
                        @if ($errors->has('url'))
                        <span class="help-block" style="color: red">{{ $errors->first('url') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>Logo</label>
                        <input type="file" class="form-control" name="logo">
                        @if ($errors->has('logo'))
                        <span class="help-block" style="color: red">{{ $errors->first('logo') }}</span>
                        @endif
                    </div>
                </div>
                <div class="kt-portlet__foot">
                    <div class="kt-form__actions">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>

            <!--end::Form-->
        </div>

@stop
@section('scripts')
<script>
</script>
@stop

resources/views/admin/companies/index.blade.php
@extends('layouts.layout.layout')
@section('head')
<title>Companies</title>
@endsection
@section('body-header')
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container  kt-container--fluid ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">
                Companies
            </h3>
            <span class="kt-subheader__separator kt-subheader__separator--v"></span>
            <div class="kt-subheader__group" id="kt_subheader_search">
                <span class="kt-subheader__desc" id="kt_subheader_total">
                    {{$companies->total()}} Total </span>
            </div>
        </div>
    </div>
</div>
@endsection

@section('body')
<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="text-right mb-3">
        <a class="btn btn-brand btn-elevate" href="{{route('company.create')}}"><i class="fa fa-plus mx-2"></i>Create a new company</a>
    </div>
    <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__body kt-portlet__body--fit">
                <div class="kt-datatable kt-datatable--default kt-datatable--brand kt-datatable--loaded" id="kt_apps_user_list_datatable" style="">
                    <table class="kt-datatable__table" style="display: block;">
                        <thead class="kt-datatable__head">
                            <tr class="kt-datatable__row" style="left: 0px;">
                                <th class="kt-datatable__cell"><span style="width: 100px;">Comapny ID</span></th>
                                <th class="kt-datatable__cell"><span style="width: 100px;">Company name</span></th>
                                <th class="kt-datatable__cell"><span style="width: 100px;">Company email</span></th>
                                <th class="kt-datatable__cell"><span style="width: 100px;">Company website</span></th>
                                <th class="kt-datatable__cell"><span style="width: 70px;">Actions</span></th>
                            </tr>
                        </thead>
                        <tbody style="" class="kt-datatable__body">
                            @foreach($companies as $key=>$company)
                            <tr data-row="{{$company->id}}" class="kt-datatable__row">
                                <td class="kt-datatable__cell--sorted kt-datatable__cell" data-field="AgentName">
                                    <span style="width: 100px;">{{$company->id}}</span>
                                </td>
                                <td class="kt-datatable__cell--sorted kt-datatable__cell" data-field="AgentName">
                                    <span style="width: 100px;">{{$company->name}}</span>
                                </td>
                                <td class="kt-datatable__cell--sorted kt-datatable__cell" data-field="AgentName">
                                    <span style="width: 100px;">{{$company->email}}</span>
                                </td>
                                <td data-field="Type" data-autohide-disabled="false" class="kt-datatable__cell">
                                    <span style="width: 100px;">{{$company->url}}</span>
                                </td>
                                <td data-field="Actions" data-autohide-disabled="false" class="kt-datatable__cell"><span style="overflow: visible; position: relative; width: 70px;">
                                        <div class="dropdown middle"> <a data-toggle="dropdown" class="btn btn-sm btn-clean btn-icon btn-icon-md"> <i class="flaticon-more-1"></i> </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <ul class="kt-nav">
                                                    <li class="kt-nav__item"> <a class="kt-nav__link" href="{{route('company.edit', $company->id)}}"> <i class="kt-nav__link-icon flaticon2-contract"></i> <span class="kt-nav__link-text">Edit Company</span> </a> </li>
                                                    <form action="{{route('company.destroy', $company->id)}}" method="post">
                                                        @csrf
                                                        @method('delete')
                                                    <li class="kt-nav__item"> <button type="submit" class="btn btn-danger btn-sm rounded-0" style="margin-left: 10px;"> <i class="fa fa-trash"></i> <span class="kt-nav__link-text">Delete Company</span> </button> </li>
                                                    </form>
                                                </ul>
                                            </div>
                                        </div>
                                    </span></td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="kt-pagination kt-pagination--brand">
                {{$companies->links()}}
            </div>
    </div>
</div>
@endsection