routes/web.php
<?php

use App\Http\Controllers\CompanyController;
use App\Http\Controllers\EmployeeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return redirect('login');
});

Auth::routes(['register' => false]);

Route::middleware(['web'])->prefix('dashboard')->group(function () {
    Route::get('/', function(){
        return view('admin.dashboard');
    })->name('DashboardHome');

    Route::resource('company', CompanyController::class);

    Route::resource('employee', EmployeeController::class);
});

app/Models/Employee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Employee extends Model
{
    use HasFactory;

    public function getNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }

    public function company(){
        return $this->belongsTo('App\Models\Company', 'company_id');
    }
}

app/Http/Controllers/EmployeeController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\EmployeeRequest;
use App\Models\Company;
use App\Models\Employee;
use Illuminate\Http\Request;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::with('company')->paginate(10);

        return view('admin.employees.index', compact('employees'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::all();
        return view('admin.employees.create', compact('companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(EmployeeRequest $request)
    {
        $employee = new Employee();
        $employee->first_name = $request->first_name;
        $employee->last_name = $request->last_name;
        $employee->phone = $request->phone;
        $employee->email = $request->email;
        $employee->company_id = $request->company_id;
        try{
            $employee->save();
        } catch(\Exception $e){
            return back()->with('error', $e->getMessage()); 
        }

        return back()->with('success', 'Created successfully!');

    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $employee = Employee::findOrFail($id);
        $companies = Company::all();

        return view('admin.employees.edit', compact('employee', 'companies'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(EmployeeRequest $request, $id)
    {
        $employee = Employee::findOrFail($id);
        $employee->first_name = $request->first_name;
        $employee->last_name = $request->last_name;
        $employee->phone = $request->phone;
        $employee->email = $request->email;
        $employee->company_id = $request->company_id;
        try{
            $employee->save();
        } catch(\Exception $e){
            return back()->with('error', $e->getMessage()); 
        }

        return back()->with('success', 'Updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        //
    }
}

resources/views/admin/employees/create.blade.php
@extends('layouts/layout/layout')

@section('head')
<title>Add an employee</title>
@endsection

@section('body')
	<!--begin::Portlet-->
    <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
                        Add an employee
                    </h3>
                </div>
            </div>

            <!--begin::Form-->
            <form class="kt-form" method="POST" action="{{route('employee.store')}}">
                @csrf
                <div class="kt-portlet__body">
                    <div class="form-group">
                        <label>First name</label>
                        <input type="text" class="form-control" name="first_name" value="{{old('first_name')}}" required>
                        @if ($errors->has('first_name'))
                        <span class="help-block" style="color: red">{{ $errors->first('first_name') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>Last name</label>
                        <input type="text" class="form-control" name="last_name" value="{{old('last_name')}}" required>
                        @if ($errors->has('last_name'))
                        <span class="help-block" style="color: red">{{ $errors->first('last_name') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>Phone</label>
                        <input type="tel" class="form-control" name="phone" value="{{old('phone')}}" required>
                        @if ($errors->has('phone'))
                        <span class="help-block" style="color: red">{{ $errors->first('phone') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="text" class="form-control" name="email" value="{{old('email')}}" required>
                        @if ($errors->has('email'))
                        <span class="help-block" style="color: red">{{ $errors->first('email') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>Company</label>
                        <select name="company_id" required class="form-control">
                            @foreach($companies as $company)
                            <option value="{{$company->id}}" {{old('company_id') == $company->id ? 'selected' : ''}}> {{$company->name}} </option>
                            @endforeach
                        </select>
                        @if ($errors->has('company_id'))
                        <span class="help-block" style="color: red">{{ $errors->first('company_id') }}</span>
                        @endif
                    </div>
                </div>
                <div class="kt-portlet__foot">
                    <div class="kt-form__actions">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>

            <!--end::Form-->
        </div>

@stop
@section('scripts')
<script>
</script>
@stop

resources/views/admin/employees/edit.blade.php
@extends('layouts/layout/layout')

@section('head')
<title>Edit an employee</title>
@endsection

@section('body')
	<!--begin::Portlet-->
    <div class="kt-portlet">
            <div class="kt-portlet__head">
                <div class="kt-portlet__head-label">
                    <h3 class="kt-portlet__head-title">
                        Edit an employee
                    </h3>
                </div>
            </div>

            <!--begin::Form-->
            <form class="kt-form" method="POST" action="{{route('employee.update', $employee->id)}}">
                @csrf
                @method('PUT')
                <div class="kt-portlet__body">
                    <div class="form-group">
                        <label>First name</label>
                        <input type="text" class="form-control" name="first_name" value="{{$employee->first_name}}" required>
                        @if ($errors->has('first_name'))
                        <span class="help-block" style="color: red">{{ $errors->first('first_name') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>Last name</label>
                        <input type="text" class="form-control" name="last_name" value="{{$employee->last_name}}" required>
                        @if ($errors->has('last_name'))
                        <span class="help-block" style="color: red">{{ $errors->first('last_name') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>Phone</label>
                        <input type="tel" class="form-control" name="phone" value="{{$employee->phone}}" required>
                        @if ($errors->has('phone'))
                        <span class="help-block" style="color: red">{{ $errors->first('phone') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>Email</label>
                        <input type="text" class="form-control" name="email" value="{{$employee->email}}" required>
                        @if ($errors->has('email'))
                        <span class="help-block" style="color: red">{{ $errors->first('email') }}</span>
                        @endif
                    </div>
                    <div class="form-group">
                        <label>Company</label>
                        <select name="company_id" required class="form-control">
                            @foreach($companies as $company)
                            <option value="{{$company->id}}" {{$employee->company_id == $company->id ? 'selected' : ''}}> {{$company->name}} </option>
                            @endforeach
                        </select>
                        @if ($errors->has('company_id'))
                        <span class="help-block" style="color: red">{{ $errors->first('company_id') }}</span>
                        @endif
                    </div>
                </div>
                <div class="kt-portlet__foot">
                    <div class="kt-form__actions">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </form>

            <!--end::Form-->
        </div>

@stop
@section('scripts')
<script>
</script>
@stop

resources/views/admin/employees/index.blade.php
@extends('layouts.layout.layout')
@section('head')
<title>Employees</title>
@endsection
@section('body-header')
<div class="kt-subheader   kt-grid__item" id="kt_subheader">
    <div class="kt-container  kt-container--fluid ">
        <div class="kt-subheader__main">
            <h3 class="kt-subheader__title">
                Employees
            </h3>
            <span class="kt-subheader__separator kt-subheader__separator--v"></span>
            <div class="kt-subheader__group" id="kt_subheader_search">
                <span class="kt-subheader__desc" id="kt_subheader_total">
                    {{$employees->total()}} Total </span>
            </div>
        </div>
    </div>
</div>
@endsection

@section('body')
<div class="kt-container  kt-container--fluid  kt-grid__item kt-grid__item--fluid">
    <div class="text-right mb-3">
        <a class="btn btn-brand btn-elevate" href="{{route('employee.create')}}"><i class="fa fa-plus mx-2"></i>Create a new employee</a>
    </div>
    <div class="kt-portlet kt-portlet--mobile">
            <div class="kt-portlet__body kt-portlet__body--fit">
                <div class="kt-datatable kt-datatable--default kt-datatable--brand kt-datatable--loaded" id="kt_apps_user_list_datatable" style="">
                    <table class="kt-datatable__table" style="display: block;">
                        <thead class="kt-datatable__head">
                            <tr class="kt-datatable__row" style="left: 0px;">
                                <th class="kt-datatable__cell"><span style="width: 100px;">Employee ID</span></th>
                                <th class="kt-datatable__cell"><span style="width: 100px;">Employee name</span></th>
                                <th class="kt-datatable__cell"><span style="width: 100px;">Employee phone</span></th>
                                <th class="kt-datatable__cell"><span style="width: 100px;">Employee email</span></th>
                                <th class="kt-datatable__cell"><span style="width: 100px;">Employee company</span></th>
                                <th class="kt-datatable__cell"><span style="width: 70px;">Actions</span></th>
                            </tr>
                        </thead>
                        <tbody style="" class="kt-datatable__body">
                            @foreach($employees as $key=>$company)
                            <tr data-row="{{$company->id}}" class="kt-datatable__row">
                                <td class="kt-datatable__cell--sorted kt-datatable__cell" data-field="AgentName">
                                    <span style="width: 100px;">{{$company->id}}</span>
                                </td>
                                <td class="kt-datatable__cell--sorted kt-datatable__cell" data-field="AgentName">
                                    <span style="width: 100px;">{{$company->name}}</span>
                                </td>
                                <td class="kt-datatable__cell--sorted kt-datatable__cell" data-field="AgentName">
                                    <span style="width: 100px;">{{$company->phone}}</span>
                                </td>
                                <td class="kt-datatable__cell--sorted kt-datatable__cell" data-field="AgentName">
                                    <span style="width: 100px;">{{$company->email}}</span>
                                </td>
                                <td class="kt-datatable__cell--sorted kt-datatable__cell" data-field="AgentName">
                                    <span style="width: 100px;">{{@$company->company->name}}</span>
                                </td>
                                <td data-field="Actions" data-autohide-disabled="false" class="kt-datatable__cell"><span style="overflow: visible; position: relative; width: 70px;">
                                        <div class="dropdown middle"> <a data-toggle="dropdown" class="btn btn-sm btn-clean btn-icon btn-icon-md"> <i class="flaticon-more-1"></i> </a>
                                            <div class="dropdown-menu dropdown-menu-right">
                                                <ul class="kt-nav">
                                                    <li class="kt-nav__item"> <a class="kt-nav__link" href="{{route('employee.edit', $company->id)}}"> <i class="kt-nav__link-icon flaticon2-contract"></i> <span class="kt-nav__link-text">Edit Employee</span> </a> </li>
                                                    <form action="{{route('employee.destroy', $company->id)}}" method="post">
                                                        @csrf
                                                        @method('delete')
                                                    <li class="kt-nav__item"> <button type="submit" class="btn btn-danger btn-sm rounded-0" style="margin-left: 10px;"> <i class="fa fa-trash"></i> <span class="kt-nav__link-text">Delete Employee</span> </button> </li>
                                                    </form>
                                                </ul>
                                            </div>
                                        </div>
                                    </span></td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="kt-pagination kt-pagination--brand">
                {{$employees->links()}}
            </div>
    </div>
</div>
@endsection